server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/vetcare_medical_records
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.10.0.4:8761/eureka/
gcp:
  storage:
    bucket-name: vetcare-files-project-e9fb8820-8459-4622-9e9

management:
  endpoints:
    web:
      exposure:
        include: "*"